language: scala
git:
  depth: 100
cache:
  directories:
    - $HOME/.ivy2/cache
    - $HOME/.sbt/boot
    - $HOME/.coursier
before_cache:
  # Cleanup locks to avoid unnecessary cache updates
  - find $HOME/.sbt -name "*.lock" | xargs rm
matrix:
  include:
    - os: linux
      jdk: oraclejdk11
      scala: 2.13.2
    - os: linux
      scala: 2.12.11
      env: JDK=graalvm-ce-20.0.0
      before_script:
        - unset -v _JAVA_OPTIONS
        - wget https://github.com/sormuras/bach/raw/master/install-jdk.sh
        - source install-jdk.sh --url https://github.com/graalvm/graalvm-ce-builds/releases/download/vm-20.0.0/graalvm-ce-java8-linux-amd64-20.0.0.tar.gz
        - echo JAVA_HOME = ${JAVA_HOME}
        - echo PATH = ${PATH}
        - ls ${JAVA_HOME}
script:
  - travis_wait 60 sbt -batch ++$TRAVIS_SCALA_VERSION! clean coverage test coverageAggregate mimaReportBinaryIssues < /dev/null
  - SCALAJS_VERSION=0.6.32 travis_wait 60 sbt -batch ++$TRAVIS_SCALA_VERSION! clean coverage test coverageAggregate mimaReportBinaryIssues < /dev/null
after_success:
  - bash <(curl -s https://codecov.io/bash)
